# Generated by Django 2.2.19 on 2022-09-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220901_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='url',
            new_name='slug',
        ),
    ]
